//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameModelContext : DbContext
    {
        public GameModelContext()
            : base("name=GameModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author> Authors { get; set; }
        public DbSet<GameParam> GameParams { get; set; }
        public DbSet<GameResult> GameResults { get; set; }
        public DbSet<Game> Games { get; set; }
        public DbSet<History> Histories { get; set; }
        public DbSet<HistoryParam> HistoryParams { get; set; }
        public DbSet<HistoryResult> HistoryResults { get; set; }
        public DbSet<Player> Players { get; set; }
    }
}
