//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameParam
    {
        public GameParam()
        {
            this.HistoryParams = new HashSet<HistoryParam>();
        }
    
        public long id { get; set; }
        public long id_game { get; set; }
        public string name { get; set; }
        public string value { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual ICollection<HistoryParam> HistoryParams { get; set; }
    }
}
