//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameModelContainer : DbContext
    {
        public GameModelContainer()
            : base("name=GameModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameParams> GameParams1 { get; set; }
        public virtual DbSet<GameResults> GameResults { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<HistoryResult> HistoryResults { get; set; }
        public virtual DbSet<HistoryParams> HistoryParams { get; set; }
    }
}
