//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GameParams = new HashSet<GameParam>();
            this.GameResults = new HashSet<GameResult>();
            this.Histories = new HashSet<History>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<long> author_id { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<GameParam> GameParams { get; set; }
        public virtual ICollection<GameResult> GameResults { get; set; }
        public virtual ICollection<History> Histories { get; set; }
    }
}
