//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GameParams = new HashSet<GameParams>();
            this.GameResults = new HashSet<GameResults>();
            this.Histories = new HashSet<History>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<GameParams> GameParams { get; set; }
        public virtual ICollection<GameResults> GameResults { get; set; }
        public virtual ICollection<History> Histories { get; set; }
    }
}
