//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryResult
    {
        public long id { get; set; }
        public Nullable<long> id_history { get; set; }
        public Nullable<long> id_game_results { get; set; }
        public decimal value { get; set; }
    
        public virtual GameResult GameResult { get; set; }
        public virtual History History { get; set; }
    }
}
