//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryParam
    {
        public long id { get; set; }
        public long id_history { get; set; }
        public long id_game_params { get; set; }
        public decimal value { get; set; }
    
        public virtual GameParam GameParam { get; set; }
        public virtual History History { get; set; }
    }
}
