//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public History()
        {
            this.HistoryResults = new HashSet<HistoryResult>();
            this.HistoryParams = new HashSet<HistoryParams>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Game Game { get; set; }
        public virtual ICollection<HistoryResult> HistoryResults { get; set; }
        public virtual ICollection<HistoryParams> HistoryParams { get; set; }
    }
}
