//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectMiniGames.Configs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameParamsList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameParamsList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinectMiniGames.Configs.GameParamsList", typeof(GameParamsList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;ApplesGame&quot;}.
        /// </summary>
        internal static string ApplesGameLevel1 {
            get {
                return ResourceManager.GetString("ApplesGameLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;ApplesGame&quot;}.
        /// </summary>
        internal static string ApplesGameLevel2 {
            get {
                return ResourceManager.GetString("ApplesGameLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;ApplesGame&quot;}.
        /// </summary>
        internal static string ApplesGameLevel3 {
            get {
                return ResourceManager.GetString("ApplesGameLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;BubblesGame&quot;}.
        /// </summary>
        internal static string BubblesGameLevel1 {
            get {
                return ResourceManager.GetString("BubblesGameLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;BubblesGame&quot;}.
        /// </summary>
        internal static string BubblesGameLevel2 {
            get {
                return ResourceManager.GetString("BubblesGameLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;BubblesGame&quot;}.
        /// </summary>
        internal static string BubblesGameLevel3 {
            get {
                return ResourceManager.GetString("BubblesGameLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;BubblesGame&quot;}.
        /// </summary>
        internal static string BubblesGameLevel4 {
            get {
                return ResourceManager.GetString("BubblesGameLevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;LettersGame&quot;}.
        /// </summary>
        internal static string LettersGameLevel1 {
            get {
                return ResourceManager.GetString("LettersGameLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;LettersGame&quot;}.
        /// </summary>
        internal static string LettersGameLevel2 {
            get {
                return ResourceManager.GetString("LettersGameLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;LettersGame&quot;}.
        /// </summary>
        internal static string LettersGameLevel3 {
            get {
                return ResourceManager.GetString("LettersGameLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;TrainOfWords&quot;}.
        /// </summary>
        internal static string TrainOfWordsLevel1 {
            get {
                return ResourceManager.GetString("TrainOfWordsLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;TrainOfWords&quot;}.
        /// </summary>
        internal static string TrainOfWordsLevel2 {
            get {
                return ResourceManager.GetString("TrainOfWordsLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;TrainOfWords&quot;}.
        /// </summary>
        internal static string TrainOfWordsLevel3 {
            get {
                return ResourceManager.GetString("TrainOfWordsLevel3", resourceCulture);
            }
        }
    }
}
