//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainOfWords.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Words5Chars {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Words5Chars() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainOfWords.Resources.Words5Chars", typeof(Words5Chars).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banan.
        /// </summary>
        internal static string banan {
            get {
                return ResourceManager.GetString("banan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baton.
        /// </summary>
        internal static string baton {
            get {
                return ResourceManager.GetString("baton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to głowa.
        /// </summary>
        internal static string głowa {
            get {
                return ResourceManager.GetString("głowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kubek.
        /// </summary>
        internal static string kubek {
            get {
                return ResourceManager.GetString("kubek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to motyl.
        /// </summary>
        internal static string motyl {
            get {
                return ResourceManager.GetString("motyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piłka.
        /// </summary>
        internal static string piłka {
            get {
                return ResourceManager.GetString("piłka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rower.
        /// </summary>
        internal static string rower {
            get {
                return ResourceManager.GetString("rower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sklep.
        /// </summary>
        internal static string sklep {
            get {
                return ResourceManager.GetString("sklep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szafa.
        /// </summary>
        internal static string szafa {
            get {
                return ResourceManager.GetString("szafa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worek.
        /// </summary>
        internal static string worek {
            get {
                return ResourceManager.GetString("worek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zegar.
        /// </summary>
        internal static string zegar {
            get {
                return ResourceManager.GetString("zegar", resourceCulture);
            }
        }
    }
}
