//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement.Configs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameResultsList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameResultsList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinectMiniGames.Configs.GameResultsList", typeof(GameResultsList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;ApplesGame&quot;, &quot;name&quot;:&quot;Correct Trials&quot;}.
        /// </summary>
        internal static string ApplesGameCorrectTrials {
            get {
                return ResourceManager.GetString("ApplesGameCorrectTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;ApplesGame&quot;,&quot;name&quot;:&quot;Failures&quot;}.
        /// </summary>
        internal static string ApplesGameFailures {
            get {
                return ResourceManager.GetString("ApplesGameFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;ApplesGame&quot;, &quot;name&quot;:&quot;Time&quot;}.
        /// </summary>
        internal static string ApplesGameTime {
            get {
                return ResourceManager.GetString("ApplesGameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;BubblesGame&quot;, &quot;name&quot;:&quot;Success&quot;}.
        /// </summary>
        internal static string BubblesGameSuccess {
            get {
                return ResourceManager.GetString("BubblesGameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;BubblesGame&quot;, &quot;name&quot;:&quot;Time&quot;}.
        /// </summary>
        internal static string BubblesGameTime {
            get {
                return ResourceManager.GetString("BubblesGameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;DrawingGame&quot;,&quot;name&quot;:&quot;Time&quot;}.
        /// </summary>
        internal static string DrawingGameTime {
            get {
                return ResourceManager.GetString("DrawingGameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;DrawingGame&quot;,&quot;name&quot;:&quot;Time Out&quot;}.
        /// </summary>
        internal static string DrawingGameTimeOut {
            get {
                return ResourceManager.GetString("DrawingGameTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;LettersGame&quot;, &quot;name&quot;:&quot;Correct Trials&quot;}.
        /// </summary>
        internal static string LettersGameCorrectTrials {
            get {
                return ResourceManager.GetString("LettersGameCorrectTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;LettersGame&quot;,&quot;name&quot;:&quot;Failures&quot;}.
        /// </summary>
        internal static string LettersGameFailures {
            get {
                return ResourceManager.GetString("LettersGameFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;LettersGame&quot;, &quot;name&quot;:&quot;Time&quot;}.
        /// </summary>
        internal static string LettersGameTime {
            get {
                return ResourceManager.GetString("LettersGameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;TrainOfWords&quot;,&quot;name&quot;:&quot;Correct Trials&quot;}.
        /// </summary>
        internal static string TrainCorrectTrials {
            get {
                return ResourceManager.GetString("TrainCorrectTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;TrainOfWords&quot;,&quot;name&quot;:&quot;Failures&quot;}.
        /// </summary>
        internal static string TrainFailures {
            get {
                return ResourceManager.GetString("TrainFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:&quot;TrainOfWords&quot;,&quot;name&quot;:&quot;Time&quot;}.
        /// </summary>
        internal static string TrainTime {
            get {
                return ResourceManager.GetString("TrainTime", resourceCulture);
            }
        }
    }
}
