//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagement.Configs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameParamsList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameParamsList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatabaseManagement.Configs.GameParamsList", typeof(GameParamsList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;ApplesGame&quot;, &quot;Name&quot;:&quot;Apples&quot;}.
        /// </summary>
        internal static string ApplesGameApples {
            get {
                return ResourceManager.GetString("ApplesGameApples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;ApplesGame&quot;, &quot;Name&quot;:&quot;Baskets&quot;}.
        /// </summary>
        internal static string ApplesGameBaskets {
            get {
                return ResourceManager.GetString("ApplesGameBaskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;ApplesGame&quot;, &quot;Name&quot;:&quot;Colors&quot;}.
        /// </summary>
        internal static string ApplesGameColors {
            get {
                return ResourceManager.GetString("ApplesGameColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;ApplesGame&quot;, &quot;Name&quot;:&quot;Trees&quot;}.
        /// </summary>
        internal static string ApplesGameTrees {
            get {
                return ResourceManager.GetString("ApplesGameTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;BubblesGame&quot;, &quot;Name&quot;:&quot;Appearance Frequency&quot;}.
        /// </summary>
        internal static string BubblesGameAppearanceFrequency {
            get {
                return ResourceManager.GetString("BubblesGameAppearanceFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;BubblesGame&quot;, &quot;Name&quot;:&quot;Bubbles&quot;}.
        /// </summary>
        internal static string BubblesGameBubbles {
            get {
                return ResourceManager.GetString("BubblesGameBubbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;BubblesGame&quot;, &quot;Name&quot;:&quot;Bubbles Size&quot;}.
        /// </summary>
        internal static string BubblesGameBubblesSize {
            get {
                return ResourceManager.GetString("BubblesGameBubblesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;BubblesGame&quot;, &quot;Name&quot;:&quot;Fall Speed&quot;}.
        /// </summary>
        internal static string BubblesGameFallSpeed {
            get {
                return ResourceManager.GetString("BubblesGameFallSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;BubblesGame&quot;, &quot;Name&quot;:&quot;Level&quot;}.
        /// </summary>
        internal static string BubblesGameLevel {
            get {
                return ResourceManager.GetString("BubblesGameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;DrawingGame&quot;, &quot;Name&quot;:&quot;Level&quot;}.
        /// </summary>
        internal static string DrawingGameLevel {
            get {
                return ResourceManager.GetString("DrawingGameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;LettersGame&quot;, &quot;Name&quot;:&quot;Level&quot;}.
        /// </summary>
        internal static string LettersGameLevel {
            get {
                return ResourceManager.GetString("LettersGameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Game&quot;:&quot;TrainOfWords&quot;, &quot;Name&quot;:&quot;Level&quot;}.
        /// </summary>
        internal static string TrainOfWordsLevel {
            get {
                return ResourceManager.GetString("TrainOfWordsLevel", resourceCulture);
            }
        }
    }
}
